CREATE TABLE IF NOT EXISTS staff (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    chapa VARCHAR(20) NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    function_name VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL
);
