CREATE TABLE IF NOT EXISTS students (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    academic_register VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    sex VARCHAR(9) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
		parent_id INTEGER REFERENCES parents(id) ON DELETE CASCADE NOT NULL
);

